### PR TITLE
workflow 7.x | using condition evaluators | LRDOCS-9253

### PR DESCRIPTION
**Pull request by rbohl**
Thanks for reviewing! This PR just adds logic to load the workflow definition that's in the src/main/resources/definitions folder of the `r6j9-impl` project.

https://issues.liferay.com/browse/LRDOCS-9253

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
Hello @rbohl, I send this [pr](https://github.com/rbohl/liferay-learn/pull/95) to you.

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Comment by rbohl** [comment]
https://github.com/rbohl/liferay-learn/pull/95

**Pull request closed without merging**
